### ISSUE TITLE
Revise metadata for pcstahar

### ISSUE THREAD

**Issue by yzhang104** [nsrr/chat-data-dictionary#329]
Use SHHS' version:
[Percentage of total sleep duration: (Apneas with no oxygen desaturation threshold used and with or without arousal + hypopneas with > 30% flow reduction and no oxygen desaturation and only with arousal)](https://sleepdata.org/datasets/shhs/variables/pcstahar)

**Comment by mrueschman** [comment]
Closed in 1f40355
